/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AlterarSenhaRouteImport } from './routes/alterar-senha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedAdministracaoRouteImport } from './routes/_authenticated/administracao'
import { Route as AuthenticatedApontarRouteImport } from './routes/_authenticated/apontar'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContagemRouteImport } from './routes/_authenticated/contagem'
import { Route as AuthenticatedControleApontamentosRouteImport } from './routes/_authenticated/controle-apontamentos'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedIndicadoresRouteImport } from './routes/_authenticated/indicadores'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedOcorrenciasRouteImport } from './routes/_authenticated/ocorrencias'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedParadasRouteImport } from './routes/_authenticated/paradas'
import { Route as AuthenticatedPassagemTurnoRouteImport } from './routes/_authenticated/passagem-turno'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedProgramacaoRouteImport } from './routes/_authenticated/programacao'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedReportarProblemaRouteImport } from './routes/_authenticated/reportar-problema'
import { Route as AuthenticatedSelecionarRouteImport } from './routes/_authenticated/selecionar'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedRelatorioRelatorioIdRouteImport } from './routes/_authenticated/relatorio.$relatorioId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaRoute = AlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdministracaoRoute =
  AuthenticatedAdministracaoRouteImport.update({
    id: '/administracao',
    path: '/administracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApontarRoute = AuthenticatedApontarRouteImport.update({
  id: '/apontar',
  path: '/apontar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContagemRoute = AuthenticatedContagemRouteImport.update({
  id: '/contagem',
  path: '/contagem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedControleApontamentosRoute =
  AuthenticatedControleApontamentosRouteImport.update({
    id: '/controle-apontamentos',
    path: '/controle-apontamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicadoresRoute =
  AuthenticatedIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOcorrenciasRoute =
  AuthenticatedOcorrenciasRouteImport.update({
    id: '/ocorrencias',
    path: '/ocorrencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParadasRoute = AuthenticatedParadasRouteImport.update({
  id: '/paradas',
  path: '/paradas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPassagemTurnoRoute =
  AuthenticatedPassagemTurnoRouteImport.update({
    id: '/passagem-turno',
    path: '/passagem-turno',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgramacaoRoute =
  AuthenticatedProgramacaoRouteImport.update({
    id: '/programacao',
    path: '/programacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportarProblemaRoute =
  AuthenticatedReportarProblemaRouteImport.update({
    id: '/reportar-problema',
    path: '/reportar-problema',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSelecionarRoute = AuthenticatedSelecionarRouteImport.update({
  id: '/selecionar',
  path: '/selecionar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatorioRelatorioIdRoute =
  AuthenticatedRelatorioRelatorioIdRouteImport.update({
    id: '/relatorio/$relatorioId',
    path: '/relatorio/$relatorioId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/apontar': typeof AuthenticatedApontarRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contagem': typeof AuthenticatedContagemRoute
  '/controle-apontamentos': typeof AuthenticatedControleApontamentosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/paradas': typeof AuthenticatedParadasRoute
  '/passagem-turno': typeof AuthenticatedPassagemTurnoRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/programacao': typeof AuthenticatedProgramacaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reportar-problema': typeof AuthenticatedReportarProblemaRoute
  '/selecionar': typeof AuthenticatedSelecionarRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/relatorio/$relatorioId': typeof AuthenticatedRelatorioRelatorioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/apontar': typeof AuthenticatedApontarRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contagem': typeof AuthenticatedContagemRoute
  '/controle-apontamentos': typeof AuthenticatedControleApontamentosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/paradas': typeof AuthenticatedParadasRoute
  '/passagem-turno': typeof AuthenticatedPassagemTurnoRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/programacao': typeof AuthenticatedProgramacaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reportar-problema': typeof AuthenticatedReportarProblemaRoute
  '/selecionar': typeof AuthenticatedSelecionarRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/relatorio/$relatorioId': typeof AuthenticatedRelatorioRelatorioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alterar-senha': typeof AlterarSenhaRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/administracao': typeof AuthenticatedAdministracaoRoute
  '/_authenticated/apontar': typeof AuthenticatedApontarRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contagem': typeof AuthenticatedContagemRoute
  '/_authenticated/controle-apontamentos': typeof AuthenticatedControleApontamentosRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/paradas': typeof AuthenticatedParadasRoute
  '/_authenticated/passagem-turno': typeof AuthenticatedPassagemTurnoRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/programacao': typeof AuthenticatedProgramacaoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/reportar-problema': typeof AuthenticatedReportarProblemaRoute
  '/_authenticated/selecionar': typeof AuthenticatedSelecionarRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/relatorio/$relatorioId': typeof AuthenticatedRelatorioRelatorioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alterar-senha'
    | '/auth'
    | '/redefinir-senha'
    | '/administracao'
    | '/apontar'
    | '/configuracoes'
    | '/contagem'
    | '/controle-apontamentos'
    | '/historico'
    | '/indicadores'
    | '/metas'
    | '/ocorrencias'
    | '/painel'
    | '/paradas'
    | '/passagem-turno'
    | '/produtos'
    | '/programacao'
    | '/relatorios'
    | '/reportar-problema'
    | '/selecionar'
    | '/usuarios'
    | '/relatorio/$relatorioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alterar-senha'
    | '/auth'
    | '/redefinir-senha'
    | '/administracao'
    | '/apontar'
    | '/configuracoes'
    | '/contagem'
    | '/controle-apontamentos'
    | '/historico'
    | '/indicadores'
    | '/metas'
    | '/ocorrencias'
    | '/painel'
    | '/paradas'
    | '/passagem-turno'
    | '/produtos'
    | '/programacao'
    | '/relatorios'
    | '/reportar-problema'
    | '/selecionar'
    | '/usuarios'
    | '/relatorio/$relatorioId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alterar-senha'
    | '/auth'
    | '/redefinir-senha'
    | '/_authenticated/administracao'
    | '/_authenticated/apontar'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contagem'
    | '/_authenticated/controle-apontamentos'
    | '/_authenticated/historico'
    | '/_authenticated/indicadores'
    | '/_authenticated/metas'
    | '/_authenticated/ocorrencias'
    | '/_authenticated/painel'
    | '/_authenticated/paradas'
    | '/_authenticated/passagem-turno'
    | '/_authenticated/produtos'
    | '/_authenticated/programacao'
    | '/_authenticated/relatorios'
    | '/_authenticated/reportar-problema'
    | '/_authenticated/selecionar'
    | '/_authenticated/usuarios'
    | '/_authenticated/relatorio/$relatorioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlterarSenhaRoute: typeof AlterarSenhaRoute
  AuthRoute: typeof AuthRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha': {
      id: '/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AlterarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/administracao': {
      id: '/_authenticated/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AuthenticatedAdministracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apontar': {
      id: '/_authenticated/apontar'
      path: '/apontar'
      fullPath: '/apontar'
      preLoaderRoute: typeof AuthenticatedApontarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contagem': {
      id: '/_authenticated/contagem'
      path: '/contagem'
      fullPath: '/contagem'
      preLoaderRoute: typeof AuthenticatedContagemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/controle-apontamentos': {
      id: '/_authenticated/controle-apontamentos'
      path: '/controle-apontamentos'
      fullPath: '/controle-apontamentos'
      preLoaderRoute: typeof AuthenticatedControleApontamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores': {
      id: '/_authenticated/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof AuthenticatedIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocorrencias': {
      id: '/_authenticated/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/ocorrencias'
      preLoaderRoute: typeof AuthenticatedOcorrenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paradas': {
      id: '/_authenticated/paradas'
      path: '/paradas'
      fullPath: '/paradas'
      preLoaderRoute: typeof AuthenticatedParadasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passagem-turno': {
      id: '/_authenticated/passagem-turno'
      path: '/passagem-turno'
      fullPath: '/passagem-turno'
      preLoaderRoute: typeof AuthenticatedPassagemTurnoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programacao': {
      id: '/_authenticated/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof AuthenticatedProgramacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportar-problema': {
      id: '/_authenticated/reportar-problema'
      path: '/reportar-problema'
      fullPath: '/reportar-problema'
      preLoaderRoute: typeof AuthenticatedReportarProblemaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/selecionar': {
      id: '/_authenticated/selecionar'
      path: '/selecionar'
      fullPath: '/selecionar'
      preLoaderRoute: typeof AuthenticatedSelecionarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio/$relatorioId': {
      id: '/_authenticated/relatorio/$relatorioId'
      path: '/relatorio/$relatorioId'
      fullPath: '/relatorio/$relatorioId'
      preLoaderRoute: typeof AuthenticatedRelatorioRelatorioIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministracaoRoute: typeof AuthenticatedAdministracaoRoute
  AuthenticatedApontarRoute: typeof AuthenticatedApontarRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContagemRoute: typeof AuthenticatedContagemRoute
  AuthenticatedControleApontamentosRoute: typeof AuthenticatedControleApontamentosRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedIndicadoresRoute: typeof AuthenticatedIndicadoresRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedOcorrenciasRoute: typeof AuthenticatedOcorrenciasRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedParadasRoute: typeof AuthenticatedParadasRoute
  AuthenticatedPassagemTurnoRoute: typeof AuthenticatedPassagemTurnoRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedProgramacaoRoute: typeof AuthenticatedProgramacaoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedReportarProblemaRoute: typeof AuthenticatedReportarProblemaRoute
  AuthenticatedSelecionarRoute: typeof AuthenticatedSelecionarRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedRelatorioRelatorioIdRoute: typeof AuthenticatedRelatorioRelatorioIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministracaoRoute: AuthenticatedAdministracaoRoute,
  AuthenticatedApontarRoute: AuthenticatedApontarRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContagemRoute: AuthenticatedContagemRoute,
  AuthenticatedControleApontamentosRoute:
    AuthenticatedControleApontamentosRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedIndicadoresRoute: AuthenticatedIndicadoresRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedOcorrenciasRoute: AuthenticatedOcorrenciasRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedParadasRoute: AuthenticatedParadasRoute,
  AuthenticatedPassagemTurnoRoute: AuthenticatedPassagemTurnoRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedProgramacaoRoute: AuthenticatedProgramacaoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedReportarProblemaRoute: AuthenticatedReportarProblemaRoute,
  AuthenticatedSelecionarRoute: AuthenticatedSelecionarRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedRelatorioRelatorioIdRoute:
    AuthenticatedRelatorioRelatorioIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlterarSenhaRoute: AlterarSenhaRoute,
  AuthRoute: AuthRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
